### ISSUE TITLE
is support controlnet and ip- adapter

### ISSUE THREAD

**Issue by libai-lab** [YangLing0818/IterComp#1]

**Comment by Cominclip** [comment]
Of course, IterComp is an enhancement based on SDXL, and it can be easily adapted to ControlNet and IP-Adapter. 
We used Canny as the condition to control IterComp, and the generated results are shown below:
![test](https://github.com/user-attachments/assets/49909294-cc2c-42b3-abd3-c76be43860eb)
We will continue to explore the potential of IterComp's extensive downstream application. Thank you for your interest!
