### ISSUE TITLE
Recommending our work on evaluation of T2I models!

### ISSUE THREAD

**Issue by linzhiqiu** [YangLing0818/IterComp#2]
Great work! I also wanted to advertise our recent work on evaluating compositional generation, which might be of interest to you:

[VQAScore](https://linzhiqiu.github.io/papers/vqascore/): VQAScore is a simple but effective automated scoring metric for image-text alignment. VQAScore strongly agrees with human judgments on compositional text prompts and can be run using one-line Python code in our repo [here](https://github.com/linzhiqiu/t2v_metrics)! It also significantly outperforms previous automated metrics such as ImageReward, HPSv2, and PickScore. Google's [Imagen3](https://arxiv.org/abs/2408.07009) reported VQAScore as the strongest replacement for CLIPScore.
[GenAI-Bench](https://linzhiqiu.github.io/papers/genai_bench/): We introduce a comprehensive benchmark for compositional image generation with 1,600 prompts written by professional designers. We also show that VQAScore can be used as a strong reward metric by re-ranking the generated candidate images. GenAI-Bench was presented as the Best Short Paper at SynData@CVPR24 workshop and was highlighted in Imagen3's report.

**Comment by Cominclip** [comment]
Thank you for your recommendation! 
Both of the works you suggested are highly valuable and solid. We will use them to conduct a more comprehensive evaluation of IterComp. We will also keep following these two works and look forward to your future high-quality research. Thank you for your interest in IterComp!

**Comment by linzhiqiu** [comment]
Thanks! Looking forward to your update and future work too!
