### ISSUE TITLE
can you teach me how to slove it?

### ISSUE THREAD

**Issue by hujinhong** [YangLing0818/IterComp#4]
Traceback (most recent call last):
  File "/home/hujh/expriement/IterComp-main/IterComp-main/data/model_gallery.py", line 1, in <module>
    from diffusers import StableDiffusionPipeline, DiffusionPipeline, StableDiffusion3Pipeline, FLUXPipeline
ImportError: cannot import name 'FLUXPipeline' from 'diffusers' (/home/hujh/anaconda3/envs/torch_base/lib/python3.9/site-packages/diffusers/__init__.py)

**Comment by Cominclip** [comment]
Thank you for your interest. We have updated the code, and it is now able to successfully build the model gallery.
