### ISSUE TITLE
关于experiment章节中的10000个prompt的疑问

### ISSUE THREAD

**Issue by 333caowei** [YangLing0818/IterComp#5]
论文experiment章节中提到3500 prompt生成的52500图片pair用于训练reward模型，然后在feed back learning时候使用了 10000个DiffusionDB的prompt。

**请问实际在diffusion训练时候是之前的3500 还是新的10000 prompt呢？** 

<img width="1059" alt="image" src="https://github.com/user-attachments/assets/743de4f7-c8aa-444a-b8b2-2e2593256111">

（论文experiment章节中的字面意思感觉是使用新的10000 prompt用于扩散模型的训练， 但是在3.3章节中有提到: "The image rankings for each prompt are updated using the trained reward model Rkθ(·), while preserving the relative ranks of the initial six images."  感觉这里有些矛盾，因为10000 prompt是没有6个外部模型的生成图像人工标注的吧。）

<img width="1097" alt="image" src="https://github.com/user-attachments/assets/bf236448-f263-4840-9dd1-f470c4208fde">

**Comment by Cominclip** [comment]
感谢您对我们项目的关注！
关于第一个问题。reward models与base diffusion model的训练是分开的，reward models使用3500个prompt以及52500个图片对进行训练，base diffusion model使用DiffusionDB的10000个prompt进行训练。reward model的训练需要针对特定的compositional任务，例如attribute binding, spatial relationship等，因此用于reward model训练的3500个prompt都是针对特定任务设计的。而base diffusion model需要有其通用性，因此使用了10000个开源的真实用户prompt来进行微调。
关于第二个问题。在当前iteration结束，即base diffusion model训练结束后，我们会用该优化后的模型对3500个用于训练reward model的prompt进行图片的采样（即将该优化后的模型添加进model gallery作为第7个模型），在保证原始6个模型生成图片的相对排名不变的情况下插入新的图片。
我们将在更新后的论文中详细阐述这一点。如果您后续仍有问题，欢迎提问或与我邮件联系。

**Comment by 333caowei** [comment]
> 感谢您对我们项目的关注！ 关于第一个问题。reward models与base diffusion model的训练是分开的，reward models使用3500个prompt以及52500个图片对进行训练，base diffusion model使用DiffusionDB的10000个prompt进行训练。reward model的训练需要针对特定的compositional任务，例如attribute binding, spatial relationship等，因此用于reward model训练的3500个prompt都是针对特定任务设计的。而base diffusion model需要有其通用性，因此使用了10000个开源的真实用户prompt来进行微调。 关于第二个问题。在当前iteration结束，即base diffusion model训练结束后，我们会用该优化后的模型对3500个用于训练reward model的prompt进行图片的采样（即将该优化后的模型添加进model gallery作为第7个模型），在保证原始6个模型生成图片的相对排名不变的情况下插入新的图片。 我们将在更新后的论文中详细阐述这一点。如果您后续仍有问题，欢迎提问或与我邮件联系。

谢谢回答，关于第二个问题我再进一步咨询下， 例如对于原始的prompt，用6个模型生成的的图片经过人工打分排序后， 对于新的第7个模型生成的图片结果，插入进去的规则，我理解是这样的：
1、假设有前6个模型生成的图片a、b、c、d、e、f ， 人工标注比如attribute binding的打分**由高到低**排序为**d、e、f、a、c、b**。 
2、现在有了第7个模型生成的图片g， 
3、使用attribute binding的reward模型对于a、b、c、d、e、f、g 图片均进行打分，假设打分后的分值**由高到低**为：**d、f、e、a、g、c、b**（**这里哪怕reward认为f得分比e高也忽略，默认使用人工标注的分数为准**），所以最终的7张图片得分排序为**d、e、f、a、g、c、b**
不知这样我理解的对不对

**Comment by Cominclip** [comment]
嗯嗯您理解是对的，在使用优化后的模型或新增模型来扩充model gallery的时候，都需要保持原始图片的相对排名不变

**Comment by shencuifeng** [comment]
你好，请问训练reward models使用的3500个prompt会开源吗
